// =====================================================
// NEXBE Contract Generator — Product Catalog
// 28 zestawów retrofit: magazyn energii + falownik hybrydowy
// Ceny brutto (8% VAT) za kompletny zestaw z montażem
// Źródło: Konfiguracja_Magazynow_Energii_Cennik.xlsx
// =====================================================

import { CatalogProduct } from '@/types/contract';

export const catalogProducts: CatalogProduct[] = [
  // ──────────── SIGENERGY (PREMIUM) ────────────
  {
    id: 'sigen-9-10kw',
    name: 'Sigenergy SigenStor AI 9 kWh',
    brand: 'Sigenergy',
    batteryModel: 'SigenStor AI 9 kWh',
    batteryCapacity_kWh: 9.0,
    inverterModel: 'Sigenergy Hybrid 10 kW',
    inverterPower_kW: 10,
    type: 'DC_HYBRID',
    segment: 'PREMIUM',
    price_gross_a: 29193,
    price_gross_b: 32772,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/sigenergy.png',
  },
  {
    id: 'sigen-12-10kw',
    name: 'Sigenergy SigenStor AI 12 kWh',
    brand: 'Sigenergy',
    batteryModel: 'SigenStor AI 12 kWh',
    batteryCapacity_kWh: 12.0,
    inverterModel: 'Sigenergy Hybrid 10 kW',
    inverterPower_kW: 10,
    type: 'DC_HYBRID',
    segment: 'PREMIUM',
    price_gross_a: 30086,
    price_gross_b: 33665,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/sigenergy.png',
  },
  {
    id: 'sigen-15-10kw',
    name: 'Sigenergy SigenStor AI 15 kWh',
    brand: 'Sigenergy',
    batteryModel: 'SigenStor AI 15 kWh',
    batteryCapacity_kWh: 15.0,
    inverterModel: 'Sigenergy Hybrid 10 kW',
    inverterPower_kW: 10,
    type: 'DC_HYBRID',
    segment: 'PREMIUM',
    price_gross_a: 41627,
    price_gross_b: 45206,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/sigenergy.png',
  },
  {
    id: 'sigen-18-10kw',
    name: 'Sigenergy SigenStor AI 18 kWh',
    brand: 'Sigenergy',
    batteryModel: 'SigenStor AI 18 kWh',
    batteryCapacity_kWh: 18.0,
    inverterModel: 'Sigenergy Hybrid 10 kW',
    inverterPower_kW: 10,
    type: 'DC_HYBRID',
    segment: 'PREMIUM',
    price_gross_a: 42519,
    price_gross_b: 46098,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/sigenergy.png',
  },
  {
    id: 'sigen-15-15kw',
    name: 'Sigenergy SigenStor AI 15 kWh (15kW)',
    brand: 'Sigenergy',
    batteryModel: 'SigenStor AI 15 kWh',
    batteryCapacity_kWh: 15.0,
    inverterModel: 'Sigenergy Hybrid 15 kW',
    inverterPower_kW: 15,
    type: 'DC_HYBRID',
    segment: 'PREMIUM',
    price_gross_a: 45353,
    price_gross_b: 48932,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/sigenergy.png',
  },
  {
    id: 'sigen-18-15kw',
    name: 'Sigenergy SigenStor AI 18 kWh (15kW)',
    brand: 'Sigenergy',
    batteryModel: 'SigenStor AI 18 kWh',
    batteryCapacity_kWh: 18.0,
    inverterModel: 'Sigenergy Hybrid 15 kW',
    inverterPower_kW: 15,
    type: 'DC_HYBRID',
    segment: 'PREMIUM',
    price_gross_a: 49994,
    price_gross_b: 53573,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/sigenergy.png',
  },
  {
    id: 'sigen-21-20kw',
    name: 'Sigenergy SigenStor AI 21 kWh (20kW)',
    brand: 'Sigenergy',
    batteryModel: 'SigenStor AI 21 kWh',
    batteryCapacity_kWh: 21.0,
    inverterModel: 'Sigenergy Hybrid 20 kW',
    inverterPower_kW: 20,
    type: 'DC_HYBRID',
    segment: 'PREMIUM',
    price_gross_a: 56398,
    price_gross_b: 59977,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/sigenergy.png',
  },
  // ──────────── SIGENERGY RETROFIT ────────────
  {
    id: 'sigen-retro-9-10kw',
    name: 'Sigenergy Retrofit 9 kWh',
    brand: 'Sigenergy',
    batteryModel: 'SigenStor AI 9 kWh (Retrofit)',
    batteryCapacity_kWh: 9.0,
    inverterModel: 'Sigenergy Hybrid TP2 10 kW',
    inverterPower_kW: 10,
    type: 'DC_HYBRID',
    segment: 'PREMIUM RETROFIT',
    price_gross_a: 25885,
    price_gross_b: 29464,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/sigenergy.png',
  },
  {
    id: 'sigen-retro-15-12kw',
    name: 'Sigenergy Retrofit 15 kWh (12kW)',
    brand: 'Sigenergy',
    batteryModel: 'SigenStor AI 15 kWh (Retrofit)',
    batteryCapacity_kWh: 15.0,
    inverterModel: 'Sigenergy Hybrid TP2 12 kW',
    inverterPower_kW: 12,
    type: 'DC_HYBRID',
    segment: 'PREMIUM RETROFIT',
    price_gross_a: 38502,
    price_gross_b: 42081,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/sigenergy.png',
  },
  // ──────────── FOXESS (STANDARD) ────────────
  {
    id: 'foxess-10-10kw',
    name: 'FoxESS ECS 10.36 kWh',
    brand: 'FoxESS',
    batteryModel: 'FoxESS ECS 10.36 kWh',
    batteryCapacity_kWh: 10.36,
    inverterModel: 'FoxESS P3-10.0-SH 10 kW',
    inverterPower_kW: 10,
    type: 'AC_RETROFIT',
    segment: 'STANDARD',
    price_gross_a: 22823,
    price_gross_b: 25754,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/foxess-ecs.png',
  },
  {
    id: 'foxess-11-10kw',
    name: 'FoxESS ECS 11.52 kWh',
    brand: 'FoxESS',
    batteryModel: 'FoxESS ECS 11.52 kWh',
    batteryCapacity_kWh: 11.52,
    inverterModel: 'FoxESS P3-10.0-SH 10 kW',
    inverterPower_kW: 10,
    type: 'AC_RETROFIT',
    segment: 'STANDARD',
    price_gross_a: 22849,
    price_gross_b: 25781,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/foxess-ecs.png',
  },
  {
    id: 'foxess-10-12kw',
    name: 'FoxESS ECS 10.36 kWh (12kW)',
    brand: 'FoxESS',
    batteryModel: 'FoxESS ECS 10.36 kWh',
    batteryCapacity_kWh: 10.36,
    inverterModel: 'FoxESS P3-12.0-SH 12 kW',
    inverterPower_kW: 12,
    type: 'AC_RETROFIT',
    segment: 'STANDARD',
    price_gross_a: 23382,
    price_gross_b: 26314,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/foxess-ecs.png',
  },
  {
    id: 'foxess-11-15kw',
    name: 'FoxESS ECS 11.52 kWh (15kW)',
    brand: 'FoxESS',
    batteryModel: 'FoxESS ECS 11.52 kWh',
    batteryCapacity_kWh: 11.52,
    inverterModel: 'FoxESS P3-15.0-SH 15 kW',
    inverterPower_kW: 15,
    type: 'AC_RETROFIT',
    segment: 'STANDARD',
    price_gross_a: 26678,
    price_gross_b: 29609,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/foxess-ecs.png',
  },
  {
    id: 'foxess-15-15kw',
    name: 'FoxESS ECS 15.54 kWh (15kW)',
    brand: 'FoxESS',
    batteryModel: 'FoxESS ECS 15.54 kWh',
    batteryCapacity_kWh: 15.54,
    inverterModel: 'FoxESS P3-15.0-SH 15 kW',
    inverterPower_kW: 15,
    type: 'AC_RETROFIT',
    segment: 'STANDARD',
    price_gross_a: 30191,
    price_gross_b: 33122,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/foxess-ecs.png',
  },
  {
    id: 'foxess-10-pro15kw',
    name: 'FoxESS PRO 10.36 kWh (15kW)',
    brand: 'FoxESS',
    batteryModel: 'FoxESS ECS 10.36 kWh',
    batteryCapacity_kWh: 10.36,
    inverterModel: 'FoxESS P3-PRO-15.0 15 kW',
    inverterPower_kW: 15,
    type: 'AC_RETROFIT',
    segment: 'STANDARD',
    price_gross_a: 28802,
    price_gross_b: 29637,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/foxess-ecs.png',
  },
  {
    id: 'foxess-20-pro20kw',
    name: 'FoxESS 20.72 kWh (20kW)',
    brand: 'FoxESS',
    batteryModel: 'FoxESS ECS 20.72 kWh',
    batteryCapacity_kWh: 20.72,
    inverterModel: 'FoxESS P3-PRO-20.0 20 kW',
    inverterPower_kW: 20,
    type: 'AC_RETROFIT',
    segment: 'STANDARD',
    price_gross_a: 41623,
    price_gross_b: 42459,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/foxess-ecs.png',
  },
  // ──────────── GOODWE LYNX (STANDARD) ────────────
  {
    id: 'goodwe-10-10kw',
    name: 'GoodWe Lynx Home U 10 kWh',
    brand: 'GoodWe',
    batteryModel: 'GoodWe Lynx Home U 10 kWh',
    batteryCapacity_kWh: 10.0,
    inverterModel: 'GoodWe GW10K-ET 10 kW',
    inverterPower_kW: 10,
    type: 'DC_HYBRID',
    segment: 'STANDARD',
    price_gross_a: 24168,
    price_gross_b: 29080,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/goodwe-lynx.png',
  },
  {
    id: 'goodwe-15-10kw',
    name: 'GoodWe Lynx Home U 15 kWh',
    brand: 'GoodWe',
    batteryModel: 'GoodWe Lynx Home U 15 kWh',
    batteryCapacity_kWh: 15.0,
    inverterModel: 'GoodWe GW10K-ET 10 kW',
    inverterPower_kW: 10,
    type: 'DC_HYBRID',
    segment: 'STANDARD',
    price_gross_a: 31918,
    price_gross_b: 36829,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/goodwe-lynx.png',
  },
  {
    id: 'goodwe-15-15kw',
    name: 'GoodWe Lynx Home U 15 kWh (15kW)',
    brand: 'GoodWe',
    batteryModel: 'GoodWe Lynx Home U 15 kWh',
    batteryCapacity_kWh: 15.0,
    inverterModel: 'GoodWe GW15K-ET 15 kW',
    inverterPower_kW: 15,
    type: 'DC_HYBRID',
    segment: 'STANDARD',
    price_gross_a: 32154,
    price_gross_b: 37066,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/goodwe-lynx.png',
  },
  {
    id: 'goodwe-20-20kw',
    name: 'GoodWe Lynx Home U 20 kWh (20kW)',
    brand: 'GoodWe',
    batteryModel: 'GoodWe Lynx Home U 20 kWh',
    batteryCapacity_kWh: 20.0,
    inverterModel: 'GoodWe GW20K-ET 20 kW',
    inverterPower_kW: 20,
    type: 'DC_HYBRID',
    segment: 'STANDARD',
    price_gross_a: 45568,
    price_gross_b: 50607,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/goodwe-lynx.png',
  },
  // ──────────── GOODWE / DYNESS (STANDARD CROSS) ────────────
  {
    id: 'goodwe-dyness-10-10kw',
    name: 'GoodWe + Dyness Tower T10 10.65 kWh',
    brand: 'GoodWe/Dyness',
    batteryModel: 'Dyness Tower T10 10.65 kWh',
    batteryCapacity_kWh: 10.65,
    inverterModel: 'GoodWe GW10K-ET 10 kW',
    inverterPower_kW: 10,
    type: 'DC_HYBRID',
    segment: 'STANDARD CROSS',
    price_gross_a: 20885,
    price_gross_b: 25796,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/dyness-tower.png',
  },
  {
    id: 'goodwe-dyness-14-15kw',
    name: 'GoodWe + Dyness Tower T10 14.2 kWh (15kW)',
    brand: 'GoodWe/Dyness',
    batteryModel: 'Dyness Tower T10 14.2 kWh',
    batteryCapacity_kWh: 14.2,
    inverterModel: 'GoodWe GW15K-ET 15 kW',
    inverterPower_kW: 15,
    type: 'DC_HYBRID',
    segment: 'STANDARD CROSS',
    price_gross_a: 24707,
    price_gross_b: 29618,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/dyness-tower.png',
  },
  // ──────────── GOODWE / BYD (STANDARD CROSS) ────────────
  {
    id: 'goodwe-byd-11-10kw',
    name: 'GoodWe + BYD 11.04 kWh',
    brand: 'GoodWe/BYD',
    batteryModel: 'BYD Battery-Box HVS 11.04 kWh',
    batteryCapacity_kWh: 11.04,
    inverterModel: 'GoodWe GW10K-ET 10 kW',
    inverterPower_kW: 10,
    type: 'DC_HYBRID',
    segment: 'STANDARD CROSS',
    price_gross_a: 30476,
    price_gross_b: 35388,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/goodwe-lynx.png',
  },
  {
    id: 'goodwe-byd-16-15kw',
    name: 'GoodWe + BYD 16.56 kWh (15kW)',
    brand: 'GoodWe/BYD',
    batteryModel: 'BYD Battery-Box HVS 16.56 kWh',
    batteryCapacity_kWh: 16.56,
    inverterModel: 'GoodWe GW15K-ET 15 kW',
    inverterPower_kW: 15,
    type: 'DC_HYBRID',
    segment: 'STANDARD CROSS',
    price_gross_a: 40410,
    price_gross_b: 45322,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/goodwe-lynx.png',
  },
  // ──────────── HUAWEI (STANDARD) ────────────
  {
    id: 'huawei-10-10kw',
    name: 'Huawei LUNA2000 10 kWh',
    brand: 'Huawei',
    batteryModel: 'Huawei LUNA2000 10 kWh',
    batteryCapacity_kWh: 10.0,
    inverterModel: 'Huawei SUN2000-10KTL-M1 10 kW',
    inverterPower_kW: 10,
    type: 'DC_HYBRID',
    segment: 'STANDARD',
    price_gross_a: 36163,
    price_gross_b: 41392,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/huawei-luna.png',
  },
  {
    id: 'huawei-15-10kw',
    name: 'Huawei LUNA2000 15 kWh',
    brand: 'Huawei',
    batteryModel: 'Huawei LUNA2000 15 kWh',
    batteryCapacity_kWh: 15.0,
    inverterModel: 'Huawei SUN2000-10KTL-M1 10 kW',
    inverterPower_kW: 10,
    type: 'DC_HYBRID',
    segment: 'STANDARD',
    price_gross_a: 46998,
    price_gross_b: 52227,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/huawei-luna.png',
  },
  {
    id: 'huawei-15-15kw',
    name: 'Huawei LUNA2000 15 kWh (15kW)',
    brand: 'Huawei',
    batteryModel: 'Huawei LUNA2000 15 kWh',
    batteryCapacity_kWh: 15.0,
    inverterModel: 'Huawei SUN2000-15KTL-M1 15 kW',
    inverterPower_kW: 15,
    type: 'DC_HYBRID',
    segment: 'STANDARD',
    price_gross_a: 50767,
    price_gross_b: 55996,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/huawei-luna.png',
  },
  {
    id: 'huawei-15-20kw',
    name: 'Huawei LUNA2000 15 kWh (20kW)',
    brand: 'Huawei',
    batteryModel: 'Huawei LUNA2000 15 kWh',
    batteryCapacity_kWh: 15.0,
    inverterModel: 'Huawei SUN2000-20KTL-M1 20 kW',
    inverterPower_kW: 20,
    type: 'DC_HYBRID',
    segment: 'STANDARD',
    price_gross_a: 51721,
    price_gross_b: 56950,
    warranty_battery_years: 10,
    warranty_inverter_years: 10,
    image: '/products/huawei-luna.png',
  },
];

// Marki falowników istniejących instalacji PV (dla formularza)
export const existingInverterBrands = [
  'Huawei', 'SolarEdge', 'Fronius', 'SMA', 'Growatt', 'Sofar',
  'GoodWe', 'Sungrow', 'FoxESS', 'Sigenergy', 'Deye', 'Afore',
  'Inna marka',
];

// Unikalne marki produktów
export const productBrands = [...new Set(catalogProducts.map(p => p.brand))];

// Grupowanie produktów po marce
export function getProductsByBrand(brand: string): CatalogProduct[] {
  return catalogProducts.filter(p => p.brand === brand);
}

// Znajdź produkt po ID
export function getProductById(id: string): CatalogProduct | undefined {
  return catalogProducts.find(p => p.id === id);
}
