import { StyleSheet } from '@react-pdf/renderer';

export const styles = StyleSheet.create({
  page: {
    fontFamily: 'Roboto',
    fontSize: 9,
    paddingTop: 60,
    paddingBottom: 60,
    paddingHorizontal: 50,
    lineHeight: 1.5,
    color: '#1a1a2e',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 30,
    paddingBottom: 15,
    borderBottomWidth: 2,
    borderBottomColor: '#B5005D',
  },
  logo: {
    width: 100,
    height: 30,
  },
  headerRight: {
    textAlign: 'right',
    fontSize: 8,
    color: '#666',
  },
  title: {
    fontSize: 13,
    fontFamily: 'Roboto-Bold',
    textAlign: 'center',
    marginBottom: 5,
    color: '#1a1a2e',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  subtitle: {
    fontSize: 9,
    textAlign: 'center',
    marginBottom: 25,
    color: '#B5005D',
    fontFamily: 'Roboto-Bold',
  },
  sectionTitle: {
    fontSize: 10,
    fontFamily: 'Roboto-Bold',
    marginTop: 18,
    marginBottom: 8,
    color: '#B5005D',
    paddingBottom: 4,
    paddingTop: 4,
    paddingLeft: 8,
    borderBottomWidth: 1.5,
    borderBottomColor: '#B5005D',
    borderLeftWidth: 3,
    borderLeftColor: '#B5005D',
    backgroundColor: '#fdf2f8',
  },
  paragraph: {
    fontSize: 9,
    marginBottom: 4,
    textAlign: 'justify',
    lineHeight: 1.6,
  },
  paragraphBold: {
    fontSize: 9,
    fontFamily: 'Roboto-Bold',
    marginBottom: 4,
  },
  indent: {
    paddingLeft: 15,
  },
  subIndent: {
    paddingLeft: 30,
  },
  row: {
    flexDirection: 'row',
    marginBottom: 3,
  },
  label: {
    width: '35%',
    fontSize: 8,
    color: '#666',
  },
  value: {
    width: '65%',
    fontSize: 9,
    fontFamily: 'Roboto-Bold',
  },
  signatureRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 50,
  },
  signatureBox: {
    width: '40%',
    textAlign: 'center',
  },
  signatureLine: {
    borderTopWidth: 0.5,
    borderTopColor: '#999',
    paddingTop: 5,
    marginTop: 40,
    fontSize: 8,
    color: '#666',
  },
  footer: {
    position: 'absolute',
    bottom: 25,
    left: 50,
    right: 50,
    textAlign: 'center',
    fontSize: 7,
    color: '#999',
    borderTopWidth: 0.5,
    borderTopColor: '#eee',
    paddingTop: 8,
  },
  pageNumber: {
    position: 'absolute',
    bottom: 25,
    right: 50,
    fontSize: 7,
    color: '#999',
  },
  checkbox: {
    width: 8,
    height: 8,
    borderWidth: 0.5,
    borderColor: '#999',
    marginRight: 5,
  },
  checkboxChecked: {
    width: 8,
    height: 8,
    borderWidth: 0.5,
    borderColor: '#B5005D',
    backgroundColor: '#B5005D',
    marginRight: 5,
  },
  table: {
    marginVertical: 10,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 0.5,
    borderBottomColor: '#eee',
    paddingVertical: 4,
  },
  tableHeader: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#B5005D',
    paddingVertical: 4,
    backgroundColor: '#f9f5ff',
  },
  tableCell: {
    fontSize: 8,
    paddingHorizontal: 4,
  },
  bold: {
    fontFamily: 'Roboto-Bold',
  },
  amountHighlight: {
    fontSize: 11,
    fontFamily: 'Roboto-Bold',
    color: '#B5005D',
    textAlign: 'center',
    marginVertical: 8,
    padding: 10,
    backgroundColor: '#fdf2f8',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#B5005D',
  },
  // Highlighted info box for important clauses
  highlightBox: {
    backgroundColor: '#f8f9fa',
    borderLeftWidth: 3,
    borderLeftColor: '#B5005D',
    padding: 8,
    marginVertical: 6,
    borderRadius: 2,
  },
  // Warning/important notice box
  warningBox: {
    backgroundColor: '#fff8f0',
    borderLeftWidth: 3,
    borderLeftColor: '#e67e22',
    padding: 8,
    marginVertical: 6,
    borderRadius: 2,
  },
  // Party header (WYKONAWCA / ZAMAWIAJĄCY)
  partyHeader: {
    fontSize: 9,
    fontFamily: 'Roboto-Bold',
    marginTop: 10,
    color: '#B5005D',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
});
